### ISSUE TITLE
trouble with coordinates

### ISSUE THREAD

**Issue by Cyberduke01** [eurostat/Nuts2json#20]
I am trying to visualize data using the Nuts2json dataset

For an example lets assume I am trying to use this specific file: https://raw.githubusercontent.com/eurostat/Nuts2json/master/2016/3035/20M/nutsrg_2.json

The problem is, each of the points have coordinates that looks as follows: 5524322.321116056,1759372.7151357569. Personally I have no idea how to relate these to coordinates used to describe a place on the earth. I would appreciate any help

**Comment by jgaffuri** [comment]
Hi,
These coordinates are in the CRS (coordinate reference system) number 3035 (see [here](https://spatialreference.org/ref/epsg/3035/))
If you need other coordinates, such as latitude and longitude, you should use CRS 4258 instead:
https://raw.githubusercontent.com/eurostat/Nuts2json/master/2016/4258/20M/nutsrg_2.json
