### ISSUE TITLE
Eurostat GISCO services down?

### ISSUE THREAD

**Issue by AlFontal** [eurostat/Nuts2json#29]
This is probably not the adequate channel to communicate this, but since the repo belongs to Eurostat, it might not be the worst either. 

I am working with several of the shapefiles for NUTS1 and NUTS2 boundaries in my analyses, usually hosted in https://gisco-services.ec.europa.eu/

It seems however, that the whole services website is down, and there is no way to access the files. I might be able to get the ones I usually use although at a different resolution in this repo, but I was just wondering whether this issue has been noted.

PD: If I could get any indication on how to get, specifically, the files usually hosted at:
+ https://gisco-services.ec.europa.eu/distribution/v2/nuts/shp/NUTS_RG_01M_2021_4326_LEVL_2.shp.zip
+ https://gisco-services.ec.europa.eu/distribution/v2/nuts/shp/NUTS_RG_01M_2021_4326_LEVL_1.shp.zip

That would be awesome!

**Comment by AlFontal** [comment]
Never mind, it's been solved as soon as I published the message :laughing:

**Comment by AlFontal** [comment]
Files have changed now, and at least the two files I was reading are not properly defined (most regions do not have an assigned geometry).

**Comment by mumins** [comment]
Dear Alejandro,

The problem is fixed.
Apologies for unavailability!

Best regards,
Uldis Polakovs

**Comment by AlFontal** [comment]
Dear @mumins, thanks for the quick reply!

I can indeed see that the source files are available and have been changed from my last check. However, I believe there might be an error with them.

When I try to read the files with Python (using `geopandas`):

```python
import geopandas as gpd

nuts2 = gpd.read_file('https://gisco-services.ec.europa.eu/distribution/v2/'
                      'nuts/shp/NUTS_RG_01M_2021_4326_LEVL_2.shp.zip')
``` 
I get the following error:

```
IllegalArgumentException: Points of LinearRing do not form a closed linestring
```
This is usually an indication that the geometries defined in the shapefile are not *closed*, and since they can't be resolved they are basically skipped.

When I open the file in QGIS, I can observe that indeed, something weird is going on:

![image](https://user-images.githubusercontent.com/10958332/98274216-6b8d2d80-1f93-11eb-9580-d44030814359.png)

 Any clues on what might be causing this?

**Comment by jgaffuri** [comment]
Dear @AlFontal
For such question, you should rather contact Eurostat user support: https://ec.europa.eu/eurostat/help/support
