### ISSUE TITLE
NUTS Map with my Statistics

### ISSUE THREAD

**Issue by uyc** [eurostat/Nuts2json#32]
Hi,
I want to create a may (NUTS2 level) with using my own statistics (instead of Eurostat). Is it possible?
Best wishes
Umut

**Comment by jgaffuri** [comment]
Yes. Here is an example of how to do it with [eurostat-map.js](https://github.com/eurostat/eurostat-map.js):
https://bl.ocks.org/jgaffuri/e10d3e5540bbf89ee572030f1b13b8e6
And here it shows how to load your own statistics, as a CSV file:
https://bl.ocks.org/jgaffuri/6bff324484f404c3e09cc2408a3e5265

Best,
julien

**Comment by uyc** [comment]
Thank you very much.
