### ISSUE TITLE
2.json for Germany has a mixture of cities and states

### ISSUE THREAD

**Issue by denis-bz** [eurostat/Nuts2json#41]
Hi Nuts2Json people
I'm confused by 2.json for Germany: level 1 has the 16 states (Bundeslaender), level 3 has 401 cities + counties,
but level 2 has a mixture of cities, states, and a few regions in Bayern.
(I wanted to use some data that appears to use level 2, very confusing ...)
If you have geopandas, could you try this please ?

Thanks, cheers
  -- denis

```
#!/usr/bin/env python3
import pandas as pd
import geopandas as gpd

print( 80 * "▄" )
pd.set_option( "display.max_colwidth", 30 )

# curl -O https://raw.githubusercontent.com/eurostat/Nuts2json/master/pub/v2/2021/4326/60M/2.json
# ls -l 2.json  # 550678

df = gpd.read_file( "2.json" )
print( 'gpd.read_file( "2.json" )' )

df = df[ df.id.str.startswith( "DE" )]
print( df )
""" -->
      id                      na                       geometry
16   DE11               Stuttgart  POLYGON ((9.65058 49.79119...
17   DE12               Karlsruhe  POLYGON ((9.60558 49.42812...
18   DE13                Freiburg  POLYGON ((8.22176 48.60393...
19   DE14                Tübingen  POLYGON ((9.94310 48.63308...
20   DE21              Oberbayern  -- a region in Bayern
...
281  DEG0               Thüringen  -- a province
"""
```

**Comment by hannesaddec** [comment]
Should have 38 records. looks like something went wrong in the export. Check https://gisco-services.ec.europa.eu/distribution/v2/nuts/nuts-2021-files.html -> [in the mean time.](https://gisco-services.ec.europa.eu/distribution/v2/nuts/geojson/NUTS_RG_60M_2021_4326_LEVL_2.geojson) until its fixed

**Comment by jgaffuri** [comment]
Dear Denis,

After checking the files with:
https://github.com/eurostat/Nuts2json/blob/master/pub/v2/2021/4326/60M/2.json
https://observablehq.com/@jgaffuri/nuts2json-validation
we could not find any issue here.

The data provided here is compliant with the NUTS legislation:
https://ec.europa.eu/eurostat/web/products-manuals-and-guidelines/-/ks-gq-20-092
which for Germany includes such mixture of states/provinces/cities at level 2.

Maybe you are looking for another type of administrative unit ?

**Comment by denis-bz** [comment]
Thanks for checking this, my problem: the mixture of cities, states, and regions is correct.
(What these level-2 districts actually do is up to the level-1 province, quite different across Germany.)

Bon weekend !
![7jan-plot-eurojson](https://user-images.githubusercontent.com/1280390/148570600-492f5131-6b30-4f43-a7ba-e0d9e54d17d4.png)

**Comment by jgaffuri** [comment]
Ich wünsche Sie auch ein schönes Wochenende !
