### ISSUE TITLE
Deprecation messages

### ISSUE THREAD

**Issue by StefanBrand** [eurostat/Nuts2json#42]
What do the deprecation messages mean that were added in Nov 2020? https://github.com/eurostat/Nuts2json/commit/6b2673dbf639c03244bc5469ae1f985ca652610c

**Comment by jgaffuri** [comment]
It is a change in the project structure. The files where initially published at the root of the project. It has now moved to the /pub/vX/ folder. Use these ones instead ! The documentation has been updated accordingly.
